name: Checks dev ESPHome

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: dmamontov/esphome-lint@main
        with:
          esphome-version: "dev"
          path: "components/ble_keyboard"
          extra-pylint-options: "--disable=unused-argument"
          use-esphome-compile: true
          esphome-compile-file: "blekeyboard.yaml"
          use-clang-format: true
          extra-clang-format-options: "-assume-filename=.clang-format"
          use-esphome-branch: true
